logging:
  level:
    root: INFO
    org.springframework.data: debug
    com.devloper.joker.redundant: debug
    com.devloper.joker.rdt_sbm.rdt: debug


rdt:
  domain:
    basePackage: com.devloper.joker.*.domain

spring:
  data:
    mongodb:
      database: rdt-v2-mongodb
  output:
    ansi: #设置支持颜色显示
      enabled: always
