spring:
  output:
    ansi:
      enabled: always
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://localhost:3306/rdt_v2_jpa?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

rdt-config:
  base-package: com.joker17.*.domain,com.joker17.*.vo
  is-modify-column-must-same-type: false #设置允许modify column类型不一致
  is-update-throw-exception: true
  show-describe: false #是否显示describe信息(debug级别默认显示)
  fill-with-logical: true
  find-by-id-with-logical: true
  update-multi-with-logical: true
  default-logical-property: status

config:
  hibernate-or-jpa: hibernate #当前实例化rdt操作对象 hibernate/jpa


logging:
  level:
    root: info
    #org.springframework: debug
    com.joker17.redundant: debug

server:
  tomcat.uri-encoding: UTF-8
  port: 8281
  connectionTimeout: 8000

