logging:
  level:
    root: INFO
    org.springframework.data: debug
    com.joker17.redundant: debug
    com.joker17.rdt_sbm.rdt: trace


rdt:
  base-package: com.joker17.*.domain
  complex-by-save-all: false #是否通过saveAll保存
  is-modify-column-must-same-type: false
  deep-clone-changed-modify: false
  update-multi-with-logical: true #更新携带逻辑状态值

spring:
  data:
    mongodb:
      database: rdt-v2-mongodb
  output:
    ansi: #设置支持颜色显示
      enabled: always
